### ISSUE TITLE
betterquesting sucks

### ISSUE THREAD

**Issue by BalaM314** [BalaM314/Omnifactory#18]
whenever upstream omnifactory pushes a qb update, we'll get screwed, because bq sucks, so it'll overwrite anything we've done.
😶

**Comment by BalaM314** [comment]
other than manually reimplementing all of upstream's changes, I see no way to solve this

**Comment by RickAstly** [comment]
no worries, og omnifactory devs have our back
https://cdn.discordapp.com/attachments/666533661428154388/864329717410430996/BetterQuesting-3.5.329.jar

**Comment by BalaM314** [comment]
oh right
