### ISSUE TITLE
AdvancedRocketry.zs calls for invalid items in craft tweaker

### ISSUE THREAD

**Issue by Good-Ol-Been** [BalaM314/Omnifactory#2]
![image](https://user-images.githubusercontent.com/1490991/126690620-76b9c8fe-aa99-4315-9a5d-739924a67ae4.png)
![image](https://user-images.githubusercontent.com/1490991/126690686-15fc0612-2251-4920-af24-9d404cbc0dec.png)
That item isn't visible at all in the Oredict, either you know something i don't or these should be changed to the AR machine chassis.

**Comment by Good-Ol-Been** [comment]
Found why i think, that machine is from libvulpes, and thus the mod it was looking in was wrong. <libvulpes:advstructuremachine>
Making a PR for that, but i'm just verifying it doesn't kill things.

**Comment by BalaM314** [comment]
Whoops! My VScode plugin let me down.
