### ISSUE TITLE
Questbook localization appears to be completely gone

### ISSUE THREAD

**Issue by Good-Ol-Been** [BalaM314/Omnifactory#6]
Version: Release 1
The questbook chapters, and quest titles are all unlocalized. Not really sure what's going on here
![image](https://user-images.githubusercontent.com/1490991/126700007-6fe05db7-c55c-4ad6-a1ed-6b5e2315cdfa.png)

**Comment by BalaM314** [comment]
What da
I assume this is related to the brok window title.

**Comment by BalaM314** [comment]
Hmm... yet another missing file.
I think this has to do with the way I built the pack.
I forked it directly from Omnifactory's gh repo, then to make the client zip, I made one with the manifest from omni's latest release and then copied overrides from here.
Strangely, the broken/nonexistant files are broken on Omni's gh repo, but not in their downloads. More investigation needed.

**Comment by BalaM314** [comment]
yeah, this file https://github.com/OmnifactoryDevs/Omnifactory/blob/dev/overrides/config/CustomMainMenu/mainmenu.json on the gh repo will cause a startup crash if included in an instance

**Comment by BalaM314** [comment]
but in the client zip (https://github.com/OmnifactoryDevs/Omnifactory/suites/3221505416/artifacts/74608713) it's fixed
